"""Add professional UI models: language enum, translations, expanded pages

Revision ID: 18d2a203f346
Revises: 4db2b2721329
Create Date: 2026-01-12 14:06:21.429982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18d2a203f346'
down_revision: Union[str, Sequence[str], None] = '4db2b2721329'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the languagepref enum type
    languagepref = sa.Enum('uk', 'de', name='languagepref')
    languagepref.create(op.get_bind())

    op.create_table('translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('value_uk', sa.Text(), nullable=True),
    sa.Column('value_de', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index(op.f('ix_translations_id'), 'translations', ['id'], unique=False)
    op.add_column('static_pages', sa.Column('title_de', sa.String(), nullable=True))
    op.add_column('static_pages', sa.Column('content_de', sa.Text(), nullable=True))
    op.add_column('static_pages', sa.Column('seo_title_uk', sa.String(), nullable=True))
    op.add_column('static_pages', sa.Column('seo_title_de', sa.String(), nullable=True))
    op.add_column('static_pages', sa.Column('seo_description_uk', sa.Text(), nullable=True))
    op.add_column('static_pages', sa.Column('seo_description_de', sa.Text(), nullable=True))
    op.alter_column('users', 'language_pref',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('uk', 'de', name='languagepref'),
               existing_nullable=True,
               postgresql_using='language_pref::languagepref')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the languagepref enum type
    languagepref = sa.Enum('uk', 'de', name='languagepref')
    languagepref.drop(op.get_bind())

    op.alter_column('users', 'language_pref',
               existing_type=sa.Enum('uk', 'de', name='languagepref'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('static_pages', 'seo_description_de')
    op.drop_column('static_pages', 'seo_description_uk')
    op.drop_column('static_pages', 'seo_title_de')
    op.drop_column('static_pages', 'seo_title_uk')
    op.drop_column('static_pages', 'content_de')
    op.drop_column('static_pages', 'title_de')
    op.drop_index(op.f('ix_translations_id'), table_name='translations')
    op.drop_table('translations')
    # ### end Alembic commands ###
