"""Expand models for auth, multi-language and workflow

Revision ID: 4db2b2721329
Revises: fb5bc7ff4060
Create Date: 2026-01-12 13:49:52.535273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4db2b2721329'
down_revision: Union[str, Sequence[str], None] = 'fb5bc7ff4060'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index(op.f('ix_global_settings_id'), 'global_settings', ['id'], unique=False)
    op.add_column('categories', sa.Column('name_de', sa.String(), nullable=True))
    op.add_column('categories', sa.Column('description_de', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('delivery_address', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('contact_phone', sa.String(), nullable=True))
    op.add_column('products', sa.Column('name_de', sa.String(), nullable=True))
    op.add_column('products', sa.Column('description_de', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    op.add_column('users', sa.Column('username', sa.String(), nullable=True))
    op.add_column('users', sa.Column('language_pref', sa.String(), nullable=True))
    op.add_column('users', sa.Column('admin_notes', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'users', ['username'])
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'admin_notes')
    op.drop_column('users', 'language_pref')
    op.drop_column('users', 'username')
    op.drop_column('users', 'email')
    op.drop_column('products', 'description_de')
    op.drop_column('products', 'name_de')
    op.drop_column('orders', 'contact_phone')
    op.drop_column('orders', 'delivery_address')
    op.drop_column('categories', 'description_de')
    op.drop_column('categories', 'name_de')
    op.drop_index(op.f('ix_global_settings_id'), table_name='global_settings')
    op.drop_table('global_settings')
    # ### end Alembic commands ###
