"""Add Region model and update Farm model with region_id and farm_type

Revision ID: 6468c17308f7
Revises: 7833adead092
Create Date: 2026-01-18 13:57:44.649356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6468c17308f7'
down_revision: Union[str, Sequence[str], None] = '7833adead092'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_de', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_regions_id'), 'regions', ['id'], unique=False)
    op.add_column('farms', sa.Column('region_id', sa.Integer(), nullable=True))
    op.add_column('farms', sa.Column('farm_type', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'farms', 'regions', ['region_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'farms', type_='foreignkey')
    op.drop_column('farms', 'farm_type')
    op.drop_column('farms', 'region_id')
    op.drop_index(op.f('ix_regions_id'), table_name='regions')
    op.drop_table('regions')
    # ### end Alembic commands ###
