"""Add farms and product metadata for Sprint 09

Revision ID: 6505bacd7dce
Revises: 18d2a203f346
Create Date: 2026-01-12 16:04:20.476465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6505bacd7dce'
down_revision: Union[str, Sequence[str], None] = '18d2a203f346'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE availabilitystatus AS ENUM ('IN_STOCK', 'OUT_OF_STOCK', 'ON_REQUEST');")
    op.create_table('farms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description_uk', sa.Text(), nullable=True),
    sa.Column('description_de', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('contact_info', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_farms_id'), 'farms', ['id'], unique=False)
    op.add_column('products', sa.Column('sku', sa.String(length=50), nullable=True))
    op.add_column('products', sa.Column('availability_status', sa.Enum('IN_STOCK', 'OUT_OF_STOCK', 'ON_REQUEST', name='availabilitystatus'), nullable=True))
    op.add_column('products', sa.Column('farm_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'products', ['sku'])
    op.create_foreign_key(None, 'products', 'farms', ['farm_id'], ['id'])
    op.drop_column('products', 'is_available')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_available', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_column('products', 'farm_id')
    op.drop_column('products', 'availability_status')
    op.drop_column('products', 'sku')
    op.drop_index(op.f('ix_farms_id'), table_name='farms')
    op.drop_table('farms')
    op.execute("DROP TYPE availabilitystatus;")
    # ### end Alembic commands ###
