"""Add image_path fields to Product, Category, Farm for Sprint 10

Revision ID: bad869430125
Revises: 6505bacd7dce
Create Date: 2026-01-12 17:10:43.664927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bad869430125'
down_revision: Union[str, Sequence[str], None] = '6505bacd7dce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('image_path', sa.String(length=255), nullable=True))
    op.add_column('farms', sa.Column('image_path', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('image_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'image_path')
    op.drop_column('farms', 'image_path')
    op.drop_column('categories', 'image_path')
    # ### end Alembic commands ###
